version: '3.4'

services:
  postgres:
    container_name: db
    image: postgres:13.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - NODE_ENV=development
    volumes:
      - 'db_data:/var/lib/postgresql/data:rw'
    restart: unless-stopped

volumes:
  db_data:
